version: "2.4"

services:
  khabarkoy-backend:
    build: .
    container_name: khabarkoy-backend
    hostname: khabarkoy-backend
    ports:
    - 8080:8080
    networks:
    - khabarkoy-networks
  khabarkoy-postgres:
    image: "postgres:11"
    container_name: khabarkoy-postgres
    hostname: khabarkoy-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=11
      - POSTGRES_DB=django
      - POSTGRES_USER=django
    ports:
    - 5432
networks:
  khabarkoy-networks:
    driver: bridge
